name: chuck_norris
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.2
  device_info_plus: ^9.0.1
  logger: ^1.3.0
  package_info_plus: ^4.0.1
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  go_router: ^11.1.1
  connectivity_plus: ^5.0.1
  get_it: ^7.6.4
  firebase_core: ^2.22.0
  firebase_analytics: ^10.6.4
  firebase_crashlytics: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.3.5
  flutter_lints: ^2.0.0
  analyzer: ^5.13.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.2
  mockito: ^5.4.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/logo/
    - env/

  fonts:
    - family: CairoPlay
      fonts:
        - asset: assets/fonts/CairoPlay-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/CairoPlay-Light.ttf
          weight: 300
        - asset: assets/fonts/CairoPlay-Regular.ttf
          weight: 400
        - asset: assets/fonts/CairoPlay-Medium.ttf
          weight: 500
        - asset: assets/fonts/CairoPlay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/CairoPlay-Bold.ttf
          weight: 700
        - asset: assets/fonts/CairoPlay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/CairoPlay-Black.ttf
          weight: 900
